/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tsukamotoexample;

import data.Permintaan;
import data.Persediaan;
import java.text.DecimalFormat;
import logical.Rule;

/**
 *
 * @author bayuirfan
 */
public class TsukamotoProduksiBarang extends javax.swing.JFrame {

    /**
     * Creates new form TsukamotoProduksiBarang
     */
    public TsukamotoProduksiBarang() {
        initComponents();
        permintaanTertinggiLabel.setText(String.valueOf(Permintaan.getTitik3()));
        persediaanTertinggiLabel.setText(String.valueOf(Persediaan.getTitik3()));
        this.setLocationRelativeTo(null);
        
        Rule.setRule(rule);
    }
    
    int[][] rule = {
        { 1,-1, 1,-1},
        { 1,-1,-1,-1},
        { 1, 1, 1, 1},
        { 1, 1,-1, 1}
    };
    
    DecimalFormat format = new DecimalFormat("#########");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        permintaanField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        persediaanField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valueField = new javax.swing.JLabel();
        hitungButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        permintaanTertinggiLabel = new javax.swing.JLabel();
        persediaanTertinggiLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        changePermintaan = new javax.swing.JMenuItem();
        changeTitikPersediaan = new javax.swing.JMenuItem();
        changeProduksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tsukamoto Production Inventory");

        permintaanField.setText("0");

        jLabel1.setText("Permintaan");

        jLabel2.setText("Persediaan");

        persediaanField.setText("0");

        jLabel3.setText("Hasil");

        valueField.setText("0");

        hitungButton.setText("Hitung Produksi");
        hitungButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel4.setText("Titik Tertinggi : ");
        jLabel4.setToolTipText("");

        permintaanTertinggiLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        permintaanTertinggiLabel.setText("0");

        persediaanTertinggiLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        persediaanTertinggiLabel.setText("0");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel5.setText("Titik Tertinggi : ");
        jLabel5.setToolTipText("");

        fileMenu.setText("File");

        changePermintaan.setText("Ganti Titik Permintaan");
        changePermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePermintaanActionPerformed(evt);
            }
        });
        fileMenu.add(changePermintaan);

        changeTitikPersediaan.setText("Ganti Titik Persediaan");
        changeTitikPersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTitikPersediaanActionPerformed(evt);
            }
        });
        fileMenu.add(changeTitikPersediaan);

        changeProduksi.setText("Ganti Titik Produksi");
        changeProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeProduksiActionPerformed(evt);
            }
        });
        fileMenu.add(changeProduksi);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(persediaanTertinggiLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permintaanTertinggiLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(permintaanField)
                        .addComponent(persediaanField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addComponent(valueField))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(hitungButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permintaanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permintaanTertinggiLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(persediaanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persediaanTertinggiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hitungButton)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valueField))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeTitikPersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTitikPersediaanActionPerformed
        // TODO add your handling code here:
        ChangePersediaanDialog dialog = new ChangePersediaanDialog();
        dialog.setVisible(true);
    }//GEN-LAST:event_changeTitikPersediaanActionPerformed

    private void changePermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePermintaanActionPerformed
        // TODO add your handling code here:
        ChangePermintaanDialog dialog = new ChangePermintaanDialog();
        dialog.setVisible(true);
    }//GEN-LAST:event_changePermintaanActionPerformed

    private void changeProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeProduksiActionPerformed
        // TODO add your handling code here:
        ChangeProduksiDialog dialog = new ChangeProduksiDialog();
        dialog.setVisible(true);
    }//GEN-LAST:event_changeProduksiActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        // TODO add your handling code here:
        Permintaan.setPermintaan(Double.valueOf(permintaanField.getText()));
        Persediaan.setPersediaan(Double.valueOf(persediaanField.getText()));
        
        Rule.getPredicate();
        Rule.getZValue();
        
        valueField.setText(format.format(Rule.getResult()) + " barang");
    }//GEN-LAST:event_hitungButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TsukamotoProduksiBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TsukamotoProduksiBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TsukamotoProduksiBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TsukamotoProduksiBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TsukamotoProduksiBarang().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changePermintaan;
    private javax.swing.JMenuItem changeProduksi;
    private javax.swing.JMenuItem changeTitikPersediaan;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton hitungButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField permintaanField;
    private javax.swing.JLabel permintaanTertinggiLabel;
    private javax.swing.JTextField persediaanField;
    private javax.swing.JLabel persediaanTertinggiLabel;
    private javax.swing.JLabel valueField;
    // End of variables declaration//GEN-END:variables
}
